global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "platform-api"
    static_configs:
      - targets: ["platform-api:8000"]
    metrics_path: /metrics

  - job_name: "platform-auth"
    static_configs:
      - targets: ["platform-auth:8001"]
    metrics_path: /metrics

  - job_name: "platform-user"
    static_configs:
      - targets: ["platform-user:8002"]
    metrics_path: /metrics

  - job_name: "platform-notification"
    static_configs:
      - targets: ["platform-notification:8003"]
    metrics_path: /metrics
